### ISSUE TITLE
Has anyone successfully deployed this code on px4?

### ISSUE THREAD

**Issue by YouthKim** [TUM-AAS/neural-mpc#2]
In fact, this code is based on [Agilicious](https://agilicious.readthedocs.io/en/latest/index.html) quadcopter drone development, but it is not open source, so I cannot reproduce this at present. Has anyone successfully deployed this code on px4 or other autopilots? I am interested in deploying this code on px4. If anyone is also interested, welcome to communicate. This is my email: 1332615700@qq .com

**Comment by Tim-Salzmann** [comment]
Hi,

Unfortunately, I can not help you with the PX4, but I want to point out that Agilicious is actually open-source now [1].

Best
Tim

[1] https://agilicious.readthedocs.io/en/main/

**Comment by YouthKim** [comment]
In fact, Agilicious requires an application to be used, but I did not receive a reply after applying. There are many people facing the same problem, so I do not regard it as open source.

**Comment by Tim-Salzmann** [comment]
Unfortunately, this is out of my power as I am not in a position to decide access to Agilicious. I will close this for now. Feel free to reach out to the Agilicious team directly.
